services:
  node_server:
    depends_on:
      - postgres
      - redis
    build:
      context: ./node_server
      dockerfile: ./dockerfile
    image: "yt20chill/ev-js:latest"
    env_file:
      - ./node_server/.env.docker
    ports:
      - "8080:8080"
    networks:
      - ev

  postgres:
    image: "postgres:16"
    restart: always
    env_file:
      - ./node_server/.env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ev

  redis:
    image: "redis:7"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ev

  py_server:
    build:
      context: ./py_server
      dockerfile: ./dockerfile
    restart: always
    image: "yt20chill/ev-py:latest"
    ports:
       - "8000:8000"
    networks:
      - ev

networks:
  ev:
    driver: bridge