FROM python:3.9-slim
WORKDIR /usr/src/app
COPY . .
EXPOSE 8000
RUN apt-get update && apt-get install -y \
    build-essential \
    libhdf5-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt

CMD ["python", "app.py"]