name: Eatvolution CICD
on:
  push:
    branches:
      # - main
      - production
jobs:
  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: accessing server
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd ~/BAD-Project-Eatvolution
            git pull origin production
            cd ./node_server
            npm i
            npm run knex migrate:latest
            cd ../py_server
            source ./.venv/bin/activate
            poetry install
            pm2 restart 0
            pm2 restart 1
          host: eatvolution.yt20chill.me
          username: ubuntu
          port: 22
          key: ${{secrets.AWS_PRIVATE_KEY}}
