name: Eatvolution CICD
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
          - uses: actions/checkout@v3
          - run: |
              cd ./node_server
              npm i
              npm run env:dummy
              npm run knex migrate:latest --env test
              npm run test

  deploy:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: accessing server
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd ~/BAD-Project-Eatvolution
            git pull origin main
            cd ./node_server
            npm i
            npm run knex migrate:latest --env production
            cd ../py_server
            source ./.venv/bin/activate
            poetry install
            pm2 restart 0
            pm2 restart 1
          host: eatvolution.yt20chill.me
          username: ubuntu
          port: 22
          key: ${{secrets.AWS_PRIVATE_KEY}}
